import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Icons.module.css'

export default function Icons() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Icons</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


        </div>
    )
}
